# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.10-slim

EXPOSE 8000

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . ./app
# CMD ["gunicorn", "--bind", "0.0.0.0:8000", "ParKING.wsgi"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]