version: '3.4'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - .:/app
    depends_on:
      - db
     
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin

  proxyserver:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - web