# Generated by Django 4.1.7 on 2023-04-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_project_tasks_department_company_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id_user', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('profile_photo', models.BinaryField(blank=True, null=True)),
                ('groups_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='departments', to='web.department')),
                ('projects', models.ManyToManyField(blank=True, related_name='projects', to='web.project')),
            ],
        ),
    ]
