# Generated by Django 4.1.5 on 2023-05-03 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_user_company_email_com_company_num_workers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='workers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
