# Generated by Django 4.1.5 on 2023-05-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_company_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
    ]
